config/routes.rb
Rails.application.routes.draw do
  root to: "topics#index"

  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

  resources :topics, only: [:index, :new, :create, :show] do
    collection do
      get 'search'
    end
  end
  resources :responses, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :topics_categories
  has_many :topics, through: :topics_categories
end

app/models/response.rb
class Response < ApplicationRecord
  belongs_to :topic, optional: true
  belongs_to :user, optional: true

  validates :content, presence: true
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user, optional: true
  has_many :responses
  accepts_nested_attributes_for :responses, allow_destroy: true
  has_many :topics_categories
  has_many :categories, through: :topics_categories

  validates :title, presence: true

  def self.search(search)
    Topic.where('title LIKE(?)', "%#{search}%") + Response.where('content LIKE(?)', "%#{search}%")
  end
end

app/models/topics_category.rb
class TopicsCategory < ApplicationRecord
  belongs_to :topic
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :topics
  has_many :responses

  validates :nickname, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

  def ensure_login
    unless user_signed_in?
      redirect_to new_user_session_path, flash: {error: '投稿するためにはログインが必要です'}
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  before_action :ensure_login, only: [:create]

  def create
    @response = Response.new(response_params)
    if @response.save
      redirect_to topic_path(@response.topic.id)
    else
      redirect_to topic_path(@response.topic.id), flash: {error: '投稿内容を入力してください'}
    end
  end

  private

  def response_params
    params.require(:response).permit(:content, :topic_id).merge(user_id: current_user.id)
  end
end

app/controllers/topics_categories_controller.rb
class TopicsCategoriesController < ApplicationController
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :ensure_login, only: [:new, :create]


  def index
    @topics = Topic.all.order(id: "desc")
  end

  def new
    @topic = Topic.new
    @topic.responses.new
    @topic.categories.new
  end

  def create
    @topic = Topic.new(topic_params)
    if @topic.save
      category_ids = params[:topic][:categories].map{|i| i.to_i}
      category_ids.each do |id|
        @topics_categories = TopicsCategory.create(topic_id: @topic.id, category_id: id)
      end
      redirect_to action: :index
    else
      flash.now[:alert] = '必須事項を入力してください。'
      render action: :new
    end
  end

  def show
    @topic = Topic.find(params[:id])
    @response = Response.new
  end

  def search
    @topics = Topic.search(params[:keyword])
    render action: :index
  end

  private

  def topic_params
    params.require(:topic).permit(:title, responses_attributes: [:content, :user_id]).merge(user_id: current_user.id)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |message_type, message|
    %div{:class => "alert alert-#{message_type}"}
      = message

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title 5.5ch
    = csrf_meta_tags
    = csp_meta_tag
    %meta{name: "viewport", content: "width=device-width, initial-scale=1, shrink-to-fit=no"}
    %link{rel: "stylesheet", href: "https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css", integrity: "sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh", crossorigin: "anonymous"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container_overflow
      .header
        .header-nav
          %h1.app-name
            %a{ href: "/" } 5.5ch
          %ul.header-contents
            %li.header-contents__content.search
              = form_with(url: search_topics_path, local: true, method: :get, class: "search-form") do |form|
                = form.text_field :keyword, placeholder: "スレッドおよびレスを検索", class: "search-input"
                = form.submit "検索", class: "search-btn"
            -if user_signed_in?
              %li.header-contents__content.name
                = current_user.nickname
              %li.header-contents__content.log_out
                = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
            -else
              %li.header-contents__content.sign_up
                = link_to "新規登録", new_user_registration_path, class: 'btn'
              %li.header-contents__content.log_in
                = link_to "ログイン", new_user_session_path, class: 'btn'
      .notice-bar
        = render 'layouts/notifications'
    = yield

app/views/topics/index.html.haml
.container
  .topics-index-wrapper
    .new-topic-btn
      = link_to 'スレッドを新規作成する', new_topic_path, class: "btn btn-primary"
    .contents
      %p.contents__blank="検索に該当するスレッドがありません" if @topics.blank?
      - @topics.each do |content|
        - if content.class == Topic
          %ul.content
            %li.content__title
              = link_to content.title, topic_path(content)
            %li.content__category
              = "カテゴリー:"
              - content.categories.each do |category|
                = "【#{category.name}】"
            %li.content__content
              =content.responses[0].content
        - else content.class == Response
          %ul.content
            %li.content__title
              = link_to content.topic.title, topic_path(content.topic)
            %li.content__category
              = "カテゴリー:"
              - content.topic.categories.each do |category|
                = "【#{category.name}】"
            %li.content__content
              =content.topic.responses[0].content

app/views/topics/new.html.haml
.container
  .topics-new-contents
    .new-content
      %h1 新しく作成するスレッドの情報を記入してください
      = form_with(model: @topic, local: true, class: "new-topic-form") do |form|
        = form.label :title, "スレッドタイトル(*必須)", class: "label"
        <br>
        = form.text_field :title, class: "form-input title"
        = form.fields_for :categories do |category|
          .new-topic-form__category
            .new-topic-form__category__input
              = category.label :name, "カテゴリー", class: "label"
              <br>
              - Category.all.each_with_index do |category, index|
                = check_box_tag 'topic[categories][]', category.id, false
                = category.name
                <br>
        = form.fields_for :responses do |response|
          .new-topic-form__response
            .new-topic-form__response__input
              = response.label :content, "1レス目の投稿(*必須)", class: "label"
              <br>
              = response.text_area :content, placeholder: "コメント内容", class: "form-input content"
              = response.hidden_field :user_id, value: current_user.id
        .new-topic-form__submit
          = form.submit "スレッドを作成する", class: "form-submit btn btn-primary"

app/views/topics/show.html.haml
.container
  .topics-show-wrapper
    %h1=@topic.title
    .contents
      - @topic.responses.each_with_index do |response, index|
        %ul.content
          %li.content__information
            = index+1
            = response.user.nickname
            = response.created_at.strftime("%Y/%m/%d %H:%M:%S")
            = "ID: #{response.user.id}"
          %li.content__text
            = response.content
    .new-response
      = form_with(model: @response, local: true, class: "new-response-form") do |form|
        = form.label :content, "レスを投稿する", class: "new-response-form__label"
        <br>
        = form.text_area :content, class: "new-response-form__text"
        = form.hidden_field :topic_id, value: @topic.id
        .new-response-form__submit
          = form.submit "書き込む", class: "form-submit btn btn-primary"

app/views/users/shared/_error_messages.html.haml
- if resource.errors.any?
  #error_explanation
    %h2
      = I18n.t("errors.messages.not_saved",                 |
        count: resource.errors.count,                       |
        resource: resource.class.model_name.human.downcase) |
    %ul
      - resource.errors.full_messages.each do |message|
        %li= message

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "ログインはこちらから", new_session_path(resource_name), class: "btn"
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "登録はこちらから", new_registration_path(resource_name), class: "btn"
  %br/
-# - if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
-#   = link_to "Forgot your password?", new_password_path(resource_name)
-#   %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/